Cortex
logzio/go-metrics-sdk pull request #1
Opened 2022-02-23 11:05 UTC by ShiranAvidov

Cortex is ours now :)

2022-03-06 17:02 UTC, Doron-Bargo requested changes
lgtm - small comments

2022-03-06 17:02 UTC, Doron-Bargo commented on go.sum
> +bazil.org/fuse v0.0.0-20160811212531-371fbbdaa898/go.mod h1:Xbm+BRKSBEpa4q4hTSxohYNQpsxXPbPry4JJWOB3LB8=
Do we really need all this packages?

2022-03-06 18:09 UTC, ShiranAvidov commented on README.md
> +            semconv.SchemaURL,
its a constant that comes with the semconv package

2022-03-06 18:10 UTC, ShiranAvidov commented on README.md
> +Replace `<<INSTRUMENTATION_NAME>>` with your instrumentation name.
just a name of the meter. in the examples they add the name as a prefix to each metric name, so I believe its like a context name.

2022-03-06 18:17 UTC, ShiranAvidov commented on README.md
> +### Asynchronous Counter
I added a link at the end of the table of the instruments, where the user can find explanations and examples of each instrument type. Basically the difference between the two is best explained by the definition of synchronous and asynchronous themselves. If the user has complicated logic that is going to take time to complete, he/she should use the asynchronous version, otherwise the synchronous.

2022-03-06 18:22 UTC, ShiranAvidov commented on go.sum
> +bazil.org/fuse v0.0.0-20160811212531-371fbbdaa898/go.mod h1:Xbm+BRKSBEpa4q4hTSxohYNQpsxXPbPry4JJWOB3LB8=
the go.sum has default checksum of list of packages + the packages that we use. when you create the go.mod file it will generate it and you dont really need to edit or modify the go.sum file.

2022-03-07 09:15 UTC, Doron-Bargo approved these changes
lgtm

2022-03-07 09:36 UTC, merged